%YAML:1.0
---
model_type: PINHOLE
camera_name: cam0
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 457.5813903808594
   fy: 457.5813903808594
   cx: 320.8541564941406
   cy: 215.27906799316406
