%YAML:1.0
---
model_type: PINHOLE
camera_name: cam1
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 456.8604736328125
   fy: 456.8604736328125
   cx: 325.2926025390625
   cy: 252.96621704101562
